name: Android CI

on:
  push:
    tags-ignore:
      - '*'
  release:
    types: [created]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up JDK 11
          uses: actions/setup-java@v4
          with:
            distribution: 'adopt'
            java-version: '11'

        - name: Cache Gradle packages
          uses: actions/cache@v4
          with:
            path: |
                ~/.gradle/caches
                ~/.gradle/wrapper
            key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
            restore-keys: |
                ${{ runner.os }}-gradle

        - name: Build with Gradle
          run: ./gradlew build

        - name: Upload APK
          uses: actions/upload-artifact@v4
          with:
            name: app-apk
            path: app/build/outputs/apk/**/*.apk

    gh-release:
        if: github.event_name == 'release'
        needs: build
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Download APK artifact
          uses: actions/download-artifact@v4
          with:
            name: app-apk
            path: app/build/outputs/apk

        - name: Upload Release APK
          run: |
            gh release create ${{ github.ref }} app/build/outputs/apk/**/*.apk --title "Release ${{ github.ref }}" --notes "Automated release of the APK."
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
